default: &default
  adapter: postgresql
  host: localhost
  username: postgres

development:
  <<: *default
  database: notification_engine_dev

test:
  <<: *default
  database: notification_engine_test
